name: 🤖 AI Code Review & PR Analysis

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  models: read

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Checkout del código
      - name: Checkout
        uses: actions/checkout@v4

      # 2. LEER src/example.js → output para el modelo
      - name: Read code to analyze
        id: code
        run: |
          CODE=$(cat src/example.js 2>/dev/null || echo "Código src/example.js no encontrado o error")
          echo "content<<EOF" >> $GITHUB_OUTPUT
          echo "$CODE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 3. Obtener contexto del PR
      - name: Get PR info
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            core.setOutput('title', pr.title);
            core.setOutput('body', pr.body || '(sin descripción)');
            core.setOutput('author', pr.user.login);

      # 4. LLAMAR GITHub MODELS API
      - name: 🔮 Call GitHub Models API
        id: models
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Código que analiza (src/example.js)
          CODE="${{ steps.code.outputs.content }}"
          
          # Datos del PR
          TITLE="${{ steps.pr.outputs.title }}"
          BODY="${{ steps.pr.outputs.body }}"
          
          # Prompt completo
          PROMPT="Eres revisor automático para estudiantes.

**CÓDIGO ANALIZADO (src/example.js):**
\`\`\`javascript
$CODE
\`\`\`

**PR INFO:**
Título: '$TITLE'
Autor: '${{ steps.pr.outputs.author }}'
